server:
  port: 8082

spring:
  application:
    name: project-service

  datasource:
    url: jdbc:mysql://localhost:3306/project_db
    username: root
    password: example@123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true
